config/routes.rb
PopulousMysql::Application.routes.draw do
  resources :branches

  resources :vouchers

  resources :contributions

  resources :events

  resources :measurements

  resources :types

  resources :issues

  resources :assignments

  resources :committees

  resources :terms

  resources :representatives

  resources :parties

  resources :cycles

  resources :seats

  resources :districts

  resources :levels

  resources :counties

  resources :states

  resources :countries

  resources :documents

  devise_for :users
  get "populous/index"
  get "populous/about"
  get "populous/legal"
  get "populous/issues"
  get "populous/reps"
  get "populous/details"
  get "populous/repdetails"
  get "populous/contribution"
  get "populous/confirm"
  get "populous/contact"

  post "populous/upvoteissue"
  post "populous/downvoteissue"
  post "populous/upvoterep"
  post "populous/downvoterep"

  root 'populous#index'

  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :committee
	belongs_to :term
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	has_many :committees
end

app/models/committee.rb
class Committee < ActiveRecord::Base
	belongs_to :branch
	belongs_to :level
	has_many :assignments
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
	belongs_to :user
	belongs_to :representative
	belongs_to :issue
	has_many :vouchers
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :states
	has_many :parties

end

app/models/county.rb
class County < ActiveRecord::Base
	belongs_to :state
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
	has_many :seats
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :level
	has_many :seats
	has_many :representatives
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :issue
	belongs_to :user
	belongs_to :representative
	belongs_to :measurement
end

app/models/issue.rb
class Issue < ActiveRecord::Base
	has_many :events
	has_many :contributions
end

app/models/level.rb
class Level < ActiveRecord::Base
	has_many :districts
	has_many :seats
	has_many :committees
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
	has_many :events
end

app/models/party.rb
class Party < ActiveRecord::Base
	belongs_to :country
	has_many :representatives
end

app/models/seat.rb
class Seat < ActiveRecord::Base
	belongs_to :district
	belongs_to :level
	belongs_to :cycle
	belongs_to :term
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :country
	has_many :counties
end

app/models/term.rb
class Term < ActiveRecord::Base
	has_many :representatives
	has_many :seats
	has_many :assignments
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :contributions
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
	belongs_to :contribution
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @contributions = Contribution.all
    respond_with(@contributions)
  end

  def show
    respond_with(@contribution)
  end

  def new
    @contribution = Contribution.new
    respond_with(@contribution)
  end

  def edit
  end

  def create
    @contribution = Contribution.new(contribution_params)
    @contribution.save
    respond_with(@contribution)
  end

  def update
    @contribution.update(contribution_params)
    respond_with(@contribution)
  end

  def destroy
    @contribution.destroy
    respond_with(@contribution)
  end

  private
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    def contribution_params
      params.require(:contribution).permit(:user_id, :representative_id, :issue_id, :value)
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/contributions/_form.html.erb
<%= form_for(@contribution) do |f| %>
  <% if @contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% @contribution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :representative_id %><br>
    <%= f.number_field :representative_id %>
  </div>
  <div class="field">
    <%= f.label :issue_id %><br>
    <%= f.number_field :issue_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing contribution</h1>

<%= render 'form' %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<h1>Listing contributions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Representative</th>
      <th>Issue</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= contribution.user_id %></td>
        <td><%= contribution.representative_id %></td>
        <td><%= contribution.issue_id %></td>
        <td><%= contribution.value %></td>
        <td><%= link_to 'Show', contribution %></td>
        <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
        <td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contribution', new_contribution_path %>

app/views/contributions/new.html.erb
<h1>New contribution</h1>

<%= render 'form' %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @contribution.user_id %>
</p>

<p>
  <strong>Representative:</strong>
  <%= @contribution.representative_id %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @contribution.issue_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @contribution.value %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>