config/routes.rb
PopulousMysql::Application.routes.draw do
  resources :branches

  resources :vouchers

  resources :contributions

  resources :events

  resources :measurements

  resources :types

  resources :issues

  resources :assignments

  resources :committees

  resources :terms

  resources :representatives

  resources :parties

  resources :cycles

  resources :seats

  resources :districts

  resources :levels

  resources :counties

  resources :states

  resources :countries

  resources :documents

  devise_for :users
  get "populous/index"
  get "populous/about"
  get "populous/legal"
  get "populous/issues"
  get "populous/reps"
  get "populous/details"
  get "populous/repdetails"
  get "populous/contribution"
  get "populous/confirm"
  get "populous/contact"

  post "populous/upvoteissue"
  post "populous/downvoteissue"
  post "populous/upvoterep"
  post "populous/downvoterep"

  root 'populous#index'

  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :committee
	belongs_to :term
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	has_many :committees
end

app/models/committee.rb
class Committee < ActiveRecord::Base
	belongs_to :branch
	belongs_to :level
	has_many :assignments
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
	belongs_to :user
	belongs_to :representative
	belongs_to :issue
	has_many :vouchers
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :states
	has_many :parties

end

app/models/county.rb
class County < ActiveRecord::Base
	belongs_to :state
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
	has_many :seats
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :level
	has_many :seats
	has_many :representatives
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :issue
	belongs_to :user
	belongs_to :representative
	belongs_to :measurement
end

app/models/issue.rb
class Issue < ActiveRecord::Base
	has_many :events
	has_many :contributions
end

app/models/level.rb
class Level < ActiveRecord::Base
	has_many :districts
	has_many :seats
	has_many :committees
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
	has_many :events
end

app/models/party.rb
class Party < ActiveRecord::Base
	belongs_to :country
	has_many :representatives
end

app/models/seat.rb
class Seat < ActiveRecord::Base
	belongs_to :district
	belongs_to :level
	belongs_to :cycle
	belongs_to :term
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :country
	has_many :counties
end

app/models/term.rb
class Term < ActiveRecord::Base
	has_many :representatives
	has_many :seats
	has_many :assignments
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :contributions
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
	belongs_to :contribution
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :set_committee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @committees = Committee.all
    respond_with(@committees)
  end

  def show
    respond_with(@committee)
  end

  def new
    @committee = Committee.new
    respond_with(@committee)
  end

  def edit
  end

  def create
    @committee = Committee.new(committee_params)
    @committee.save
    respond_with(@committee)
  end

  def update
    @committee.update(committee_params)
    respond_with(@committee)
  end

  def destroy
    @committee.destroy
    respond_with(@committee)
  end

  private
    def set_committee
      @committee = Committee.find(params[:id])
    end

    def committee_params
      params.require(:committee).permit(:level_id, :name)
    end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/committees/_form.html.erb
<%= form_for(@committee) do |f| %>
  <% if @committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% @committee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level_id %><br>
    <%= f.number_field :level_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committees/edit.html.erb
<h1>Editing committee</h1>

<%= render 'form' %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

app/views/committees/index.html.erb
<h1>Listing committees</h1>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @committees.each do |committee| %>
      <tr>
        <td><%= committee.level_id %></td>
        <td><%= committee.name %></td>
        <td><%= link_to 'Show', committee %></td>
        <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
        <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Committee', new_committee_path %>

app/views/committees/new.html.erb
<h1>New committee</h1>

<%= render 'form' %>

<%= link_to 'Back', committees_path %>

app/views/committees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Level:</strong>
  <%= @committee.level_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @committee.name %>
</p>

<%= link_to 'Edit', edit_committee_path(@committee) %> |
<%= link_to 'Back', committees_path %>